/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edd4;

/**
 *
 * @author David Discua
 */
public class MASTER extends javax.swing.JFrame {

    /**
     * Creates new form MASTER
     */
    public MASTER() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        tf_nombrePlan = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        jToggleButton2 = new javax.swing.JToggleButton();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        cb_planesDisponibles = new javax.swing.JComboBox();
        Calcular = new javax.swing.JToggleButton();
        jPanel4 = new javax.swing.JPanel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        cb_planes = new javax.swing.JComboBox();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(760, 570));
        setMinimumSize(new java.awt.Dimension(760, 570));
        setPreferredSize(new java.awt.Dimension(760, 570));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Como llevar tus clases?");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 10, 490, 70);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 80, 760, 10);

        jPanel1.setBackground(new java.awt.Color(233, 230, 230));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(0, 320, 200, 10);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Ingresar Clases");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 200, 110, 30);
        jPanel1.add(tf_nombrePlan);
        tf_nombrePlan.setBounds(30, 130, 150, 30);

        jToggleButton1.setText("Agregar");
        jPanel1.add(jToggleButton1);
        jToggleButton1.setBounds(50, 330, 105, 23);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Ingresar Plan Estudio");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 20, 150, 30);

        jToggleButton2.setText("Ingresar");
        jPanel1.add(jToggleButton2);
        jToggleButton2.setBounds(60, 250, 80, 23);
        jPanel1.add(jSeparator4);
        jSeparator4.setBounds(0, 60, 200, 10);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Nombre");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 90, 60, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 120, 200, 370);

        jPanel2.setBackground(new java.awt.Color(224, 218, 218));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);
        jPanel2.add(jSeparator3);
        jSeparator3.setBounds(0, 60, 200, 10);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Estudio");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(40, 20, 130, 30);

        jPanel2.add(cb_planesDisponibles);
        cb_planesDisponibles.setBounds(30, 100, 140, 30);

        Calcular.setBackground(new java.awt.Color(204, 204, 204));
        Calcular.setText("Calcular");
        jPanel2.add(Calcular);
        Calcular.setBounds(50, 210, 110, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(520, 120, 200, 370);

        jPanel4.setBackground(new java.awt.Color(225, 225, 225));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(null);
        jPanel4.add(jSeparator5);
        jSeparator5.setBounds(0, 60, 200, 10);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Planes de Estudio");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(40, 20, 130, 30);

        jPanel4.add(cb_planes);
        cb_planes.setBounds(30, 100, 140, 30);

        jToggleButton5.setText("Borrar");
        jPanel4.add(jToggleButton5);
        jToggleButton5.setBounds(60, 250, 70, 23);

        jToggleButton6.setText("Ver");
        jPanel4.add(jToggleButton6);
        jToggleButton6.setBounds(60, 200, 70, 23);

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 106, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 106, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel5);
        jPanel5.setBounds(40, 180, 110, 110);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(270, 120, 200, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MASTER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MASTER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MASTER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MASTER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MASTER().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Calcular;
    private javax.swing.JComboBox cb_planes;
    private javax.swing.JComboBox cb_planesDisponibles;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JTextField tf_nombrePlan;
    // End of variables declaration//GEN-END:variables
}
